### ISSUE TITLE
How to access item from localStorage?

### ISSUE THREAD

**Issue by TheoMer** [Malpaux/apollo-offline#2]
@MLPXBrachmann So I'm attempting to access the following item (token) in localStorage:

```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHA...","__typename":"SigninPayload"}}
```

`localStorage.getItem('reduxPersist:apollo');` 

gives me the entire localStocrage state, but when I do 

`localStorage.getItem('token');` 

I get a null value back.

What am I overlooking here?

Many thanks in advance

**Comment by psamim** [comment]
I think if the app is loaded and you want to access the data inside Apollo store, you should use Apollo API itself, instead of looking into the `localStorage` directly. You can query the Apollo store and retrieve the cache.

If you want to have access to pending requests, they are part of the redux store, to be precise `offline.outbox`. There reside all of the pending mutations.

You can also save the data you need, e.g. `token`, somewhere inside the redux store and let `redux-offline` do the persisting and re-hydration job. So you do not need to get the item from the `localStorage` directly.

**Comment by TheoMer** [comment]
Actually I'm looking for the equivalent method known as getStoredState in redux-offline, which allows me to obtain the token id as follows:

```
    getStoredState({ storage: localForage }, (err, state = {}) => {
      req.options.headers['authorization'] = state.auth ? `Bearer ${state.auth.token}` : null;
      next();
    });
```

**Comment by PaulBrachmann** [comment]
@TheoMer Think of ```localStorage``` as a simple key-value store. ReduxPersist writes all top-level fields of the Redux store to ```localStorage['reduxPersist:[key]']``` (accessible via ```localStorage.getItem('reduxPersist:[key])```). Apollo occupies such a top-level field in your app's Redux store and thus is accessible as mentioned.

As long as you do not manually write your auth token to the localStorage (using ```localStorage.setItem('token', /* Your token here */);```), it won't be available there.

Judging from the token's ```__typename``` field, I'm assuming you are currently handling authentication directly via GraphQL (you are passing log-in details via GraphQL queries/mutations). In this case you should additionally look out that the user's clear text credentials are not cached in the browser, as this might pose a security threat. I'd recommend you to manually query the GraphQL backend and store the returned token in the localStorage yourself.

The code would look something like this:
```javascript
/* Your setup here */

export const store = createStore(
  combineReducers({ apollo: client.reducer() }),
  undefined,
  compose(
    applyMiddleware(client.middleware()),
    enhancer({
      ...config,
      persistCallback: () => {
        const token = localStorage.getItem('token');
        if (token) {
          // User is already logged in
        } else {
          // Request credentials (assuming you are using a networkInterface wrapped by Apollo-Offline)
          networkInterface.networkInterface.query({
            query: /* Your query/mutation here */,
            variables: /* Query variables here */,
          }).then((result) => {
            console.log(result);

            // Here you have to check if a valid token was returned (were the credentials correct?)

            localStorage.setItem(
              'token',
              /* Token extracted from query/mutation result */
            );
          }).catch((err) => { console.error('Network error: ', err) });
        }
      },
    }),
  ),
);
```

**EDIT:**
@psamim Is absolutely correct, it probably is a better solution to write to the Redux store instead of directly using the Web Storage API (including ```localStorage```). Having said that, you could still use the code above, but you would replace calls to ```localStorage.setItem('token', /* ... */)``` by ```store.dispatch(/* Action */)``` (an appropriate reducer would be necessary) and calls to ```localStorage.getItem('token')``` would become ```store.getState().token```

**Comment by PaulBrachmann** [comment]
@TheoMer If you are looking for something like ```getStoredState```, you are in luck.  
Apollo-Offline uses Redux-Offline under the hood (which in turn is built on Redux-Persist) and thus you should be able to use Redux-Persist's original ```getStoredState``` method without any complications.

You would still have to write the user's authentication details to the Redux store though.
